apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storageclass.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.storageclass.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageclass.size }}
