kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageclass.name }}
  annotations:
      storageclass.kubernetes.io/is-default-class: "true"
provisioner: {{ .Values.storageclass.provisioner }}
parameters:
  type: {{ .Values.storageclass.type }}
  fsType: {{ .Values.storageclass.fs }}
reclaimPolicy: Delete


